---
version: '3.7'

services:
  web:
    image: croneu/neos:7.3
    ports:
      - '8080:8080'
      - '1122:22'
    links:
      - db:db
    environment:
      WWW_PORT: 8080
      REPOSITORY_URL: https://github.com/neos/neos-development-distribution
      ADMIN_PASSWORD: 'password'
      VERSION: '4.3'
      IMPORT_GITHUB_PUB_KEYS: ${GITHUB_USERNAME}
  db:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - /var/lib/data
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  data:

networks:
  default:
