#!/usr/bin/with-contenv /bin/bash

set -e

# Choose composer v1 or v2
if [ ! -z "$COMPOSER_MAJOR_VERSION" ]; then
  if [ ! -x "/usr/local/bin/composer${COMPOSER_MAJOR_VERSION}" ]; then
    echo "* ERROR: Desired composer v${COMPOSER_MAJOR_VERSION} does not exist!"
  else
    echo "* Choosing composer v${COMPOSER_MAJOR_VERSION}"
    rm -f /usr/local/bin/composer
    ln -s /usr/local/bin/composer${COMPOSER_MAJOR_VERSION} /usr/local/bin/composer
  fi
fi

echo "* Configuring PHP $(php -r "echo PHP_VERSION;")"

# Configure PHP setting based on environment variables
echo "date.timezone=${PHP_TIMEZONE:-UTC}" > $PHP_INI_DIR/conf.d/date_timezone.ini
echo "memory_limit=${PHP_MEMORY_LIMIT:-4096M}" > $PHP_INI_DIR/conf.d/memory_limit.ini
echo "upload_max_filesize=${PHP_UPLOAD_MAX_FILESIZE:-1024M}" > $PHP_INI_DIR/conf.d/upload_max_filesize.ini
echo "post_max_size=${PHP_UPLOAD_MAX_FILESIZE:-1024M}" > $PHP_INI_DIR/conf.d/post_max_size.ini
echo "allow_url_include=${PHP_ALLOW_URL_INCLUDE:-1}" > $PHP_INI_DIR/conf.d/allow_url_include.ini
echo "max_execution_time=${PHP_MAX_EXECUTION_TIME:-240}" > $PHP_INI_DIR/conf.d/max_execution_time.ini
echo "max_input_vars=${PHP_MAX_INPUT_VARS:-1500}" > $PHP_INI_DIR/conf.d/max_input_vars.ini

# We only need one timezone data
apk add --no-cache -q tzdata >/dev/null
cp /usr/share/zoneinfo/${PHP_TIMEZONE:-UTC} /etc/localtime
apk del -q tzdata
