ARG IMAGE_VERSION="latest"

FROM croneu/neos:${IMAGE_VERSION}
MAINTAINER Remus Lazar <rl@cron.eu>

# install jre, selenium, firefox and xvfb
RUN apk add --no-cache openjdk8 xorg-server xvfb firefox-esr curl libvncserver openssl dbus \
  && curl -sSL -o /usr/bin/selenium-server-standalone.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar

# we do compile x11vnc from sources (unfortunately there is no binary package available..)
RUN apk add --no-cache --virtual=.x11vncdeps gcc g++ automake autoconf make openssl-dev libx11-dev libvncserver-dev \
  && mkdir -p /src && cd /src \
  && git clone https://github.com/LibVNC/x11vnc \
  && cd x11vnc \
  && ./autogen.sh \
  && make \
  && make install \
  && apk del .x11vncdeps \
  && cd / && rm -rf /src

# required for the xvfb notifyoncheck script
RUN apk add --no-cache xdpyinfo

ENV \
  DISPLAY=:99 \
  SCREEN_DIMENSION=1600x1000x24 \
  VNC_PASSWORD=password

COPY container-files-behat /

EXPOSE 4444 5900

ENV FLOW_CONTEXT Development/Behat
ENV DB_DATABASE db_behat
