name: "Deploy Image to DockerHub"

on:
  push:
    branches:
      - master

jobs:
  # Build a docker image for a specific version and using a given target
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ base, behat ]
        php-version: [7.2, 7.3]
        include:
          - target: base
            docker-tag: ''
          - target: behat
            docker-tag: '-behat'
            # use specific alpine versions for various php versions
          - php-version: 7.2
            alpine-version: 3.8
          - php-version: 7.3
            alpine-version: 3.8
          - php-version: 8
            alpine-version: 3.16

    steps:
      -
        name: "Checkout Sourcecode"
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      -
        name: "Cache Docker layers"
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.php-version }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.php-version }}-${{ matrix.target }}-
            ${{ runner.os }}-buildx-${{ matrix.php-version }}-
      -
        name: Docker BuildX ${{ matrix.php-version }} (${{ matrix.target }}) (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --target ${{ matrix.target }} \
            --build-arg PHP_VERSION="${{ matrix.php-version }}" \
            --output "type=image,push=false" \
            --tag croneu/neos:${{ matrix.php-version }}${{ matrix.docker-tag }} \
            --file ./Dockerfile ./
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker BuildX php ${{ matrix.php-version }} (${{ matrix.target }}) (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --target ${{ matrix.target }} \
            --build-arg PHP_VERSION="${{ matrix.php-version }}" \
            --output "type=image,push=true" \
            --tag croneu/neos:${{ matrix.php-version }}${{ matrix.docker-tag }} \
            --file ./Dockerfile ./
